version: "2"

services:
  vault_server:
    networks:
      - develop
    image: "cypherhat/vault-ethereum:latest"
    ports:
      - "9200:9200"
    volumes:
      - "./config:/home/vault/config:rw" #inside the container the root.crt file is available at /home/vault/config/root.crt
    entrypoint: /home/vault/config/entrypoint.sh
  ganache:
    networks:
      - develop
    image: trufflesuite/ganache:latest
    platform: linux/arm64 # Explicitly use ARM64 for M3 compatibility

    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    command:
      - --deterministic
      - --db=/ganache_data
      - --networkId
      - "8545"
      - --host
      - "0.0.0.0"
networks:
  develop:
    name: vault-ethereum-net
    driver: bridge
